# Project information
site_name: 'Product Integration'
site_description: 'A Discord Bot for giving roles through coupons'
site_author: 'AXVin'
site_url: 'https://axvin.tk/client_project'

# Repository
repo_name: 'AXVin/client_project'
repo_url: 'https://github.com/AXVin/client_project'



# Copyright
copyright: 'Copyright &copy; 2019 - 2020 AXVin'

nav:
    - Home: index.md
    - New Plan: new_plan.md
    - How To Use: how_to.md
    - Final Plan: final.md


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/AXVin'
    - type: 'twitter'
      link: 'https://twitter.com/_AXVin_'
    - type: 'bitbucket'
      link: 'https://bitbucket.org/AXVin'
  version: 1.0

# Extensions
markdown_extensions:
    - footnotes
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - meta
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde